### PR TITLE
Provide lib/noStyles which doesn't need less-loader

### LINKED ISSUE #34: less-loader is required
When running my webpack configuration, the build is failing over this line:
`require('../less/default.less');`
Since I do not have `less-loader` in my project, it does not know how to handle `.less` files.

What do you think will be the right solution to this? precompile the css? have it as an external file to include in the project?

I am curious to so learn your opinion about that. Thanks! :D

### PR DESCRIPTION
**Pull request by dmnd**
I'm trying to use this in a project where I already use lodash and don't
want to add less-loader. Before this PR, my options were:

1. `require('react-telephone-input/dist/react-telephone-input')`
   This includes a lot of lodash that I already include in my app.
2. `require('react-telephone-input')`
   This requires that I add less-loader because `index.js` requires a
   less file. I'd rather not do that for one dependency.

This commit introduces an alternative way to require:

`require('react-telephone-input/lib/noStyles')`

This allows applications to use this project without having to duplicate
lodash dependencies, and without having to run less-loader.

Fixes #34

### CODE REVIEW

File: src/ReactTelephoneInput.js [hunk 1]
```diff
@@ -0,0 +1,509 @@
+'use strict';
```
Comment (dmnd) [inline src/ReactTelephoneInput.js]: This file is moved from `index.js`. The only modification is the removal of the `require('../less/default.less');` — everything else is the same.

File: src/noStyles.js [hunk 2]
```diff
@@ -0,0 +1,3 @@
+'use strict';
+var ReactTelephoneInput = require('./ReactTelephoneInput');
+module.exports = ReactTelephoneInput;
```
Comment (dmnd) [inline src/noStyles.js]: Applications can require this file to get the telephone input without the styles.

**Comment by dmnd** [comment]
Note that I didn't include built files in this PR. Let me know if you'd prefer that I added them.

**Comment by mukeshsoni** [comment]
Thanks @dmnd. Appreciate it.

I am getting merge conflicts and don't know enough git to resolve it in a pull request. Can you please send another pull request or educate me on how to resolve the merge conflicts on the pull request?

**Comment by dmnd** [comment]
Let me rebase on master for you. One minute.

**Comment by mukeshsoni** [comment]
I feel the default import should be without the less file and with less should be a special file.  Like

```
require('react-telephone-input/lib/withStyles')
```

What do you say?

**Comment by dmnd** [comment]
Yeah, I agree with that, but it's a breaking change, so you'd have to release version 3.

**Comment by mukeshsoni** [comment]
Yup. Ok, i will merge this change of yours, cut a minor release.
Then change it so that without less is the default export and cut a major release.

**Comment by dmnd** [comment]
Ok just bear with me while I figure out this merge conflict :smile:

**Comment by dmnd** [comment]
Ok, rebased.

Personally I wouldn't bother with releasing the minor release if I were you. Just merge, change it so that no styles is the default, and then release.

I don't think there's a use case for staying on v2 but wanting the no styles. Anyone who wants that should upgrade to 3.

**Comment by mukeshsoni** [comment]
That makes sense.

**Comment by dmnd** [comment]
Awesome, thanks for merging so promptly! :bow:

**Comment by mukeshsoni** [comment]
Have cut a new release 3.0.0. Let me know if it works ok for you. 

And thanks for this. I wanted to remove the lessify dependency for a long time.
